---
- name: Send Notificacion
  hosts: all
  become: true
  
  tasks:

  - name: Example playbook sending mail to root
    community.general.mail:
      subject: System {{ ansible_hostname }} has been successfully provisioned.
      delegate_to: localhost

  - name: Sending an e-mail using Gmail SMTP servers
    community.general.mail:
      host: smtp.gmail.com
      port: 587
      username: reportes.automatizados@gmail.com
      password: lbruwodaqnzpepdb
      to: Adrian Bonino <adrian.bonino@la.logicalis.com>
      subject: Ansible-report
      body: System {{ ansible_hostname }} has been successfully provisioned.
    delegate_to: localhost
