---
- name: Cisco banner
  hosts: all
  remote_user: admin

  tasks:
    - name: show facts
      debug: msg="{{  ansible_facts }}"
  
    - name: run show version on remote devices
      cisco.nxos.nxos_command:
        commands: show version
      register: version

    - debug: msg="{{ version.stdout }}" 

    - name: Sending an e-mail using Gmail SMTP servers
      community.general.mail:
        host: smtp.gmail.com
        port: 587
        username: reportes.automatizados@gmail.com
        password: lbruwodaqnzpepdb
        to: Adrian Bonino <adrian.bonino@la.logicalis.com>
        subject: Ansible-report
        body: "{{ version.stdout }}"
      delegate_to: localhost

    
